services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=1

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
